### ISSUE TITLE
Create C# components using custom templates

### ISSUE THREAD

**Issue by bard83** [bard83/csharpextensions#9]
Based on [this](https://github.com/KreativJos/csharpextensions/issues/113) request, the extension should be able to support custom templates.
The user should be able to define the sections which wants to customize, then using the  menu item will be able to choose the template  - from a list of templates - and then insert the name.

Tasks

- [x]  template definition
- [x]  template selection
- [x]  template bundling

**Comment by bard83** [comment]
@heggi I'd appreciate some feedback.

**Comment by bard83** [comment]
left open in case some request or problem is opened.

**Comment by bard83** [comment]
Possible improvements:
- Definition of generics, actually the generic where part could be specified but not a Generic type itself like `MyClass<T>`.
- Record template (? not sure)

**Comment by bard83** [comment]
closed by #10

**Comment by heggi** [comment]
Thanks. 
It worked 👍 
I have an idea about some improves. I'm going to create a new issue.
